---
- hosts: localhost
  connection: local
  tasks:

  - name: Install libselinux-python
    package:
      name: python2-libselinux
      state: installed
    become: true

  - name: Install buildah
    package:
      name: buildah
      state: installed
    become: true

  - name: Install podman
    package:
      name: podman
      state: installed
    become: true
